name: GC Express Removal
description: Request to remove a gene express entry from the website
title: "[GC Express]: "
labels: [genevalidity, gcexpress]
assignees: toneillbroad
body:
  - type: input
    id: requester
    attributes:
      label: Requester Name
      description: Name of the stakeholder initiating the request. This can be different than the user entering the issue.
      placeholder: ex. Kelsea Chang
    validations:
      required: true
  - type: input
    id: requester-contact
    attributes:
      label: Requester Contact Info
      description: How can we get in touch with the original requester if we need more info?
      placeholder: ex. kchang@broadinstitute.org or @Kelsea Chang
    validations:
      required: true
  - type: input
    id: gcexpress-entry-url
    attributes:
      label: GC Express Entry Website URL
      description: The full website URL of the GC Express entry to be removed
      placeholder: ex. https://search.clinicalgenome.org/kb/gene-validity/CGGCIEX:assertion_8492
    validations:
      required: true
  - type: textarea
    id: notes
    attributes:
      label: Additional Notes
      description: If there are any additional requirements outside the norm of simply removing the entry please provide them here
