prefix gci: <http://gci.clinicalgenome.org/>

construct {
  
  ?classification a :sepio/GeneValidityEvidenceLevelAssertion ;
  :sepio/has-subject ?proposition ;
  :sepio/has-predicate :sepio/HasEvidenceLevel ;
  :sepio/has-object ?evidencelevel ;
  :sepio/has-evidence-line ?experimentalEvidenceLine, ?geneticEvidenceLine ;
  :sepio/evidence-line-strength-score ?evidencePointsTotal .

}
where {

  ?classification a gci:provisionalClassification .
  ?proposition a gci:gdm .
  
  ?classification gci:autoClassification ?evidencelevel .

  ?classification gci:classificationPoints ?pointsTree .
  
  ?pointsTree gci:evidencePointsTotal ?evidencePointsTotal .
  
}
