prefix gci: <http://dataexchange.clinicalgenome.org/gci/>
construct
{
  ?classification :sepio/has-evidence   ?geneticEvidenceLine .
  
  ?geneticEvidenceLine a :sepio/OverallGeneticEvidenceLine ;
  :sepio/evidence-line-strength-score ?geneticEvidenceTotal .
}
where
{
  ?classification a gci:provisionalClassification ;
  gci:approvedClassification true ;
  gci:classificationPoints ?pointsTree .

  ?pointsTree gci:geneticEvidenceTotal ?geneticEvidenceTotal .

  BIND (IRI(CONCAT(str(?classification), "_overall_genetic_evidence_line")) AS ?geneticEvidenceLine) .
}
