prefix gci: <http://dataexchange.clinicalgenome.org/gci/>

construct
{
  ?geneticEvidenceEvidenceLine :sepio/has-evidence
  ?autosomalDominantOtherVariantEvidenceLine ,
  ?autosomalDominantNullVariantEvidenceLine ,
  ?autosomalDominantDeNovoVariantEvidenceLine .
  
  ?autosomalDominantOtherVariantEvidenceLine a :sepio/OverallAutosomalDominantOtherVariantEvidenceLine ;
  :sepio/evidence-line-strength-score ?probandWithOtherVariantTypeWithGeneImpactTotal .

  ?autosomalDominantNullVariantEvidenceLine a :sepio/OverallAutosomalDominantNullVariantEvidenceLine ;
  :sepio/evidence-line-strength-score ?probandWithPredictedOrProvenNullVariantTotal .

  ?autosomalDominantDeNovoVariantEvidenceLine a :sepio/OverallAutosomalDominantDeNovoVariantEvidenceLine ;
  :sepio/evidence-line-strength-score ?variantIsDeNovoTotal .
}
where
{
  ?classification a gci:provisionalClassification ;
  gci:approvedClassification true ;
  gci:classificationPoints ?pointsTree .

  BIND (IRI(CONCAT(str(?classification), "_overall_genetic_evidence_line")) AS ?geneticEvidenceEvidenceLine) .
  
  ?pointsTree gci:autosomalDominantOrXlinkedDisorder ?autosomalDominantOrXlinkedDisorderTree .

  ?autosomalDominantOrXlinkedDisorderTree gci:probandWithOtherVariantTypeWithGeneImpact ?probandWithOtherVariantTypeWithGeneImpactTree .
  ?probandWithOtherVariantTypeWithGeneImpactTree gci:pointsCounted ?probandWithOtherVariantTypeWithGeneImpactTotal .

  ?autosomalDominantOrXlinkedDisorderTree gci:probandWithPredictedOrProvenNullVariant ?probandWithPredictedOrProvenNullVariantTree .
  ?probandWithPredictedOrProvenNullVariantTree gci:pointsCounted ?probandWithPredictedOrProvenNullVariantTotal .

  ?autosomalDominantOrXlinkedDisorderTree gci:variantIsDeNovo ?variantIsDeNovoTree .
  ?variantIsDeNovoTree gci:pointsCounted ?variantIsDeNovoTotal .

  BIND(IRI(CONCAT(str(?classification), "_ad_other_el")) AS ?autosomalDominantOtherVariantEvidenceLine) .
  BIND(IRI(CONCAT(str(?classification), "_ad_null_el")) AS ?autosomalDominantNullVariantEvidenceLine) .
  BIND(IRI(CONCAT(str(?classification), "_ad_dn_el")) AS ?autosomalDominantDeNovoVariantEvidenceLine) .
  
}
