prefix gci: <http://dataexchange.clinicalgenome.org/gci/>
construct
{
  ?classification :sepio/has-evidence   ?geneticEvidenceCriterionAssessment .
  
  # ?geneticEvidenceLine a :sepio/GeneticEvidenceLine ;
  # :sepio/has-evidence-item ?geneticEvidenceCriterionAssessment ;
  # :sepio/evidence-line-strength-score ?geneticEvidenceTotal .

  ?geneticEvidenceCriterionAssessment a :sepio/GeneticEvidenceCriterionAssessment ;
  :sepio/evidence-line-strength-score ?geneticEvidenceTotal .
}
where
{
  ?classification a gci:provisionalClassification .
  ?classification gci:classificationPoints ?pointsTree .

  ?pointsTree gci:geneticEvidenceTotal ?geneticEvidenceTotal .

  BIND (IRI(CONCAT(str(?classification), "_genetic_evidence_criterion_assessment")) AS ?geneticEvidenceCriterionAssessment) .
  # BIND (IRI(CONCAT(str(?classification), "_genetic_evidence_line")) AS ?geneticEvidenceLine) .
}
