prefix gci: <http://dataexchange.clinicalgenome.org/gci/>

construct
{
  ?geneticEvidenceLine :sepio/has-evidence ?caseControlEvidenceLine , ?segregationEvidenceLine .

  ?caseControlEvidenceLine a :sepio/OverallCaseControlEvidenceLine ;
  :sepio/evidence-line-strength-score ?caseControlTotal .

  ?segregationEvidenceLine a :sepio/OverallSegregationEvidenceLine ;
  :sepio/evidence-line-strength-score ?segregationTotal .
  
}
where
{

  ?classification a gci:provisionalClassification .

  BIND (IRI(CONCAT(str(?classification), "_genetic_evidence_overall_evidence_line")) AS ?geneticEvidenceLine) .
  
  ?classification gci:classificationPoints ?pointsTree .

  ?pointsTree gci:segregation ?segregationTree .
  ?segregationTree gci:pointsCounted ?segregationTotal .

  ?pointsTree gci:caseControl ?caseControlTree .
  ?caseControlTree gci:pointsCounted ?caseControlTotal .

  BIND (IRI(CONCAT(str(?classification), "_cc_el")) AS ?caseControlEvidenceLine) .
  BIND (IRI(CONCAT(str(?classification), "_seg_el")) AS ?segregationEvidenceLine) .
}
