prefix gci: <http://dataexchange.clinicalgenome.org/gci/>
prefix gcixform: <http://dataexchange.clinicalgenome.org/gcixform/>
construct {
  ?evidenceLine a ?evidenceLineType ;
  :sepio/evidence-line-strength-score ?score ;
  :sepio/has-evidence ?evidenceItem , ?functionEvidenceItem ;
  :sepio/calculated-score ?resultCalculatedScore ;
  :dc/description ?evidenceLineDescription .

  ?evidenceItem a ?evidenceItemType ;
  :sepio/is-about-allele ?variant ;
  :dc/source ?article ;
  :geno/allele-origin ?alleleOrigin ;
  :geno/has-zygosity ?zygosity ;
  :rdfs/label ?individualLabel .

  ?individual a :sepio/ProbandWithVariantEvidenceItem ;
  :sepio/has-variant ?evidenceItem .

  ?functionEvidenceItem a :sepio/VariantFunctionalImpactEvidenceItem ;
  :dc/description ?functionalDataExplanation .

}
where {

  ?evidenceLine a gci:variantScore ;
  gci:variantType ?variantType ;
  gci:variantScored ?variant ;
  gci:deNovo ?deNovo ;
  gci:calculatedScore ?calculatedScore .

  BIND(IF(?deNovo = "Yes", :geno/DeNovoAlleleOrigin , :geno/AlleleOrigin ) AS ?alleleOrigin) .
  
  OPTIONAL {
    ?evidenceLine gci:functionalDataExplanation ?functionalDataExplanation ;
    BIND(IRI(CONCAT(STR(?evidenceLine), "_function_evidence_item")) AS ?functionEvidenceItem) .
  }

  BIND(IRI(CONCAT(STR(?evidenceLine), "_variant_evidence_item")) AS ?evidenceItem) .

  OPTIONAL {
    ?evidenceLine gci:scoreExplanation ?evidenceLineDescription .
  }
  
  ?variantType gcixform:hasEvidenceLineType ?evidenceLineType ;
  gcixform:hasEvidenceItemType ?evidenceItemType .

  OPTIONAL  {
    ?evidenceLine gci:score ?adjustedScore .
  }
  
  BIND(COALESCE(?adjustedScore, ?calculatedScore) AS ?baseScore) .

  ?individual gci:variantScores ?evidenceLine ;
  gci:label ?individualLabel .

  OPTIONAL {
    ?individual gci:recessiveZygosity ?zygosity .
  }

  BIND(IF( bound(?zygosity) && ?zygosity = :geno/Homozygous , ?baseScore * 2 , ?baseScore) AS ?score) .

  BIND(IF( bound(?zygosity) && ?zygosity = :geno/Homozygous , ?calculatedScore * 2 , ?calculatedScore) AS ?resultCalculatedScore) .
  
  ?annotation  gci:individuals|gci:individualIncluded ?individual ;
  ^gci:familyIncluded? / ^(gci:families|gci:groups)? / gci:article ?publication .
  
  ?publication gci:pmid ?pmid .
  BIND(IRI(CONCAT(?pmbase, ?pmid)) AS ?article) .
  
}
