prefix gci: <http://dataexchange.clinicalgenome.org/gci/>
prefix gcixform: <http://dataexchange.clinicalgenome.org/gcixform/>
construct {
  ?evidenceLine  a ?evidenceLineType ;
  :dc/description ?scoreDescription ;
  :sepio/has-evidence ?evidenceItem ;
  :sepio/calculated-score ?calcuatedScore ;
  :sepio/evidence-line-strength-score ?score .

  ?evidenceItem  a ?evidenceItemType ;
  :dc/description ?evidenceDescription ;
  :dc/source ?article ;
  :rdfs/label ?evidenceLabel .
}
where {
  ?evidenceLine a gci:evidenceScore ;
  gci:calculatedScore ?calculatedScore .

  OPTIONAL {
    ?evidenceLine gci:scoreExplanation ?scoreDescription .
  }

  OPTIONAL  {
    ?evidenceLine gci:score ?adjustedScore .
  }

  BIND(COALESCE(?adjustedScore, ?calculatedScore) AS ?score) .
  
  ?evidenceItem gci:scores ?evidenceLine ;
  gci:label ?evidenceLabel ;
  gci:evidenceType ?gciType .

  OPTIONAL {
    ?evidenceItem gci:biochemicalFunction / gci:evidenceForFunction ?biochemicalFunctionDescription .
  }

  OPTIONAL {
    ?evidenceItem gci:proteinInteractions / gci:relationshipOfOtherGenesToDisese ?proteinInteractionDescription .
  }

  OPTIONAL {
    ?evidenceItem gci:expression / ( gci:alteredExpression | gci:normalExpression )  / gci:evidence ?expressionDescription .
  }
  
  
  BIND(COALESCE(?expressionDescription, ?proteinInteractionDescription, ?biochemicalFunctionDescription) AS ?evidenceDescription) .
  
  ?evidenceLineType gcixform:hasGCIType ?gciType ;
  gcixform:hasEvidenceItemType ?evidenceItemType ;
  gcixform:usedIn gcixform:Functional .

  ?annotation gci:experimentalData ?evidenceItem ;
  gci:article ?publication .
  
  ?publication gci:pmid ?pmid .
  BIND(IRI(CONCAT(?pmbase, ?pmid)) AS ?article) .
 }
