prefix gci: <http://dataexchange.clinicalgenome.org/gci/>
construct
{
  ?geneticEvidenceLine :sepio/has-evidence
  ?autosomalRecessiveVariantEvidenceLine .
  
  ?autosomalRecessiveVariantEvidenceLine a :sepio/OverallAutosomalRecessiveVariantEvidenceLine ;
  :sepio/evidence-line-strength-score ?autosomalRecessiveDisorderTotal .  
}
where
{
  ?classification a gci:provisionalClassification ;
  gci:approvedClassification true ;
  gci:classificationPoints ?pointsTree .

  BIND (IRI(CONCAT(str(?classification), "_overall_genetic_evidence_line")) AS ?geneticEvidenceLine) .

  ?pointsTree gci:autosomalRecessiveDisorder ?autosomalRecessiveDisorderTree .
  ?autosomalRecessiveDisorderTree gci:pointsCounted  ?autosomalRecessiveDisorderTotal .

  BIND (IRI(CONCAT(str(?classification), "_ar_el")) AS ?autosomalRecessiveVariantEvidenceLine) .

}
