prefix gci: <http://dataexchange.clinicalgenome.org/gci/>
prefix gcixform: <http://dataexchange.clinicalgenome.org/gcixform/>
construct {
  ?family  a ?evidenceLineType ;
  :dc/description ?scoreDescription ;
  :sepio/has-evidence ?segregationIRI ;
  :sepio/evidence-line-strength-score ?lodScore .

  ?segregationIRI  a ?evidenceItemType ;
  :dc/description ?evidenceDescription ;
  :dc/source ?article ;
  :rdfs/label ?evidenceLabel .
}
where {
  ?family a gci:family ;
  gci:segregation ?segregation ;
  gci:label ?evidenceLabel .

  ?segregation gci:includeLodScoreInAggregateCalculation true ;
  gci:sequencingMethod ?gciType .

  ?evidenceLineType gcixform:hasGCIType ?gciType ;
  gcixform:hasEvidenceItemType ?evidenceItemType .

  ?annotation gci:families ?family ;
  gci:article ?publication .
  ?publication gci:pmid ?pmid .
  BIND(IRI(CONCAT(?pmbase, ?pmid)) AS ?article) .

  optional {
    ?segregation gci:publishedLodScore ?publishedLodScore .
  }

  optional {
    ?segregation gci:estimatedLodScore ?estimatedLodScore .
  }

  BIND(COALESCE(?estimatedLodScore, ?publishedLodScore) AS ?lodScore) .

  BIND(CONCAT(STR(?family), "seg") AS ?segregationIRI) .

}
