prefix gci: <http://dataexchange.clinicalgenome.org/gci/>

construct {
  ?classification :sepio/qualified-contribution _:contrib .

  _:contrib :sepio/has-agent ?secondaryContributor ;
  :bfo/realizes :sepio/SecondaryContributorRole .
}
where {
  ?classification a gci:provisionalClassification ;
  gci:approvedClassification true ;
  gci:classificationContributors ?secondaryContributorID .

  BIND(IRI(CONCAT(?affbase, ?secondaryContributorID)) AS ?secondaryContributor) .
}
