prefix gci: <http://gci.clinicalgenome.org/>

construct {
  
  ?classification a :sepio/GeneValidityEvidenceLevelAssertion ;
  :sepio/has-subject ?proposition ;
  :sepio/has-predicate :sepio/HasEvidenceLevel ;
  :sepio/has-object ?evidencelevel ;
  :sepio/has-evidence-line ?experimentalEvidenceLine, ?geneticEvidenceLine ;
  :sepio/qualified-contribution ?contribution ;
  :dc/description ?description ;
  :sepio/evidence-line-strength-score ?evidencePointsTotal .

  ?contribution :sepio/has-agent ?affiliation ;
  :sepio/activity-date ?classificationDate .

}
where {
  
  ?proposition a gci:gdm ;
  gci:affiliation ?affiliationID .

  BIND(IRI(CONCAT(?affbase, ?affiliationID)) AS ?affiliation) .

  ?classification a gci:provisionalClassification ;
  gci:evidenceSummary ?description ;
  gci:autoClassification ?evidencelevel ;
  gci:classificationDate ?classificationDate ;
  gci:classificationPoints ?pointsTree .

  BIND(IRI(CONCAT(STR(?classification), "_contrib")) AS ?contribution ) .
  
  ?pointsTree gci:evidencePointsTotal ?evidencePointsTotal .
  
}
