prefix gci: <http://dataexchange.clinicalgenome.org/gci/>
prefix gcixform: <http://dataexchange.clinicalgenome.org/gcixform/>
construct {
  ?family  a ?evidenceLineType ;
  :dc/description ?scoreDescription ;
  :sepio/has-evidence ?segregationIRI ;
  :sepio/evidence-line-strength-score ?lodScore .

  ?segregationIRI  a ?evidenceItemType ;
  :dc/description ?evidenceDescription ;
  :dc/source ?article ;
  :rdfs/label ?evidenceLabel .
}
where {
  ?family a gci:family ;
  gci:segregation ?segregation ;
  gci:label ?evidenceLabel .

  # Limit to scored segregations
  # ?segregation gci:includeLodScoreInAggregateCalculation true .
  OPTIONAL {
    ?segregation gci:sequencingMethod ?gciType .
    ?declaredEvidenceLineType gcixform:hasGCIType ?gciType .
  }

  # Bind specific type if identified, if not, use generic segregation evidence line
  BIND(COALESCE(?declaredEvidenceLineType, <http://purl.obolibrary.org/obo/SEPIO_0004036>) AS ?evidenceLineType)

  # gcixform:hasEvidenceItemType ?evidenceItemType .

  # ?annotation gci:families ?family ;
  # gci:article ?publication .
  # ?publication gci:pmid ?pmid .
  # BIND(IRI(CONCAT(?pmbase, ?pmid)) AS ?article) .

  # optional {
  #   ?segregation gci:publishedLodScore ?publishedLodScore .
  # }

  # optional {
  #   ?segregation gci:estimatedLodScore ?estimatedLodScore .
  # }

  # BIND(COALESCE(?estimatedLodScore, ?publishedLodScore) AS ?lodScore) .

  BIND(CONCAT(STR(?family), "seg") AS ?segregationIRI) .

}
