prefix gci: <http://gci.clinicalgenome.org/>
construct
{
  ?geneticEvidenceCriterionAssessment :sepio/has-evidence
  ?autosomalRecessiveVariantEvidenceLine .
  
  ?autosomalRecessiveVariantCriterionAssessment a :sepio/AutosomalRecessiveVariantCriterionAssessment ;
  :sepio/evidence-line-strength-score ?autosomalRecessiveDisorderTotal .  
}
where
{
  ?classification a gci:provisionalClassification .

  BIND (IRI(CONCAT(str(?classification), "_genetic_evidence_criterion_assessment")) AS ?geneticEvidenceCriterionAssessment) .

  ?classification gci:classificationPoints ?pointsTree .

  ?pointsTree gci:autosomalRecessiveDisorder ?autosomalRecessiveDisorderTree .
  ?autosomalRecessiveDisorderTree gci:pointsCounted  ?autosomalRecessiveDisorderTotal .

  BIND (IRI(CONCAT(str(?classification), "_ar_ca")) AS ?autosomalRecessiveVariantCriterionAssessment) .

}
