prefix gci: <http://gci.clinicalgenome.org/> 
prefix gcixform: <http://dataexchange.clinicalgenome.org/gcixform/>
construct {
  ?evidenceLine  a ?evidenceLineType ;
  :dc/description ?scoreDescription ;
  :sepio/evidence-line-strength-score ?score .

  ?evidenceItem  a ?evidenceItemType ;
  :dc/description ?evidenceDescription ;
  :dc/source ?article ;
  :rdfs/label ?evidenceLabel .
}
where {
  ?evidenceLine a gci:evidenceScore ;
  gci:calculatedScore ?calculatedScore .

  OPTIONAL {
    ?evidenceLine gci:scoreExplanation ?scoreDescription .
  }

  OPTIONAL  {
    ?gciScore gci:score ?adjustedScore .
  }
  
  BIND(COALESCE(?adjustedScore, ?calculatedScore) AS ?score) .
  
  ?evidenceItem gci:scores ?evidenceLine ;
  gci:rescue ?gciRescue  ;
  gci:label ?evidenceLabel .

  ?gciRescue gci:rescueMethod ?evidenceDescription ;
  gci:rescueType ?gciType .

  ?evidenceLineType gcixform:hasGCIType ?gciType ;
  gcixform:hasEvidenceItemType ?evidenceItemType ;
  gcixform:usedIn gcixform:Rescue .

  ?annotation gci:experimentalData ?gciEvidence ;
  gci:article ?publication .
  ?publication gci:pmid ?pmid .
  BIND(IRI(CONCAT(?pmbase, ?pmid)) AS ?article) .  
 
}
