prefix gci: <http://gci.clinicalgenome.org/> 
prefix gcixform: <http://dataexchange.clinicalgenome.org/gcixform/>
construct {
  ?evidenceLine  a ?evidenceLineType ;
  :dc/description ?scoreDescription ;
  :sepio/has-evidence ?evidenceItem ;
  :sepio/evidence-line-strength-score ?score .

  ?evidenceItem  a ?evidenceItemType ;
  :dc/description ?evidenceDescription ;
  :dc/source ?article ;
  :rdfs/label ?evidenceLabel .
}
where {
  ?evidenceLine a gci:evidenceScore ;
  # TODO no calculatedScore/adjustedScore--validate that this is correct
  gci:score ?score .
  # see gci:comments below
  # gci:scoreExplanation ?scoreDescription ;

  ?evidenceItem gci:scores ?evidenceLine ;
  gci:label ?evidenceLabel ;
  # # TODO, comments attached to the evidence item are really an explanation for the score
  # # in this case--be sure to validate this
  gci:comments ?scoreDescription ;
  gci:studyType ?gciType .

  ?annotation gci:caseControlStudies ?evidenceItem ;
  gci:article ?publication .
  ?publication gci:pmid ?pmid .
  BIND(IRI(CONCAT(?pmbase, ?pmid)) AS ?article) .

  ?evidenceLineType gcixform:hasGCIType ?gciType ;
  gcixform:hasEvidenceItemType ?evidenceItemType .

}
