prefix gci: <http://dataexchange.clinicalgenome.org/gci/>
prefix gcixform: <http://dataexchange.clinicalgenome.org/gcixform/>
construct {
  ?evidenceLine a ?evidenceLineType ;
  :sepio/evidence-line-strength-score ?score ;
  :sepio/has-evidence ?evidenceItem , ?functionEvidenceItem ;
  :sepio/calculated-score ?resultCalculatedScore ;
  :sepio/score-status ?scoreStatus ;
  :sepio/is-denovo ?deNovo ;
  :dc/description ?evidenceLineDescription .

  ?evidenceItem a ?evidenceItemType ;
  :sepio/is-about-allele ?variant ;
  :dc/source ?article ;
  :geno/allele-origin ?alleleOrigin ;
  :geno/has-zygosity ?zygosity ;
  :rdfs/label ?individualLabel .

  ?individual a :sepio/ProbandWithVariantEvidenceItem ;
  :sepio/has-sex ?sex ;
  :sepio/age-unit ?ageUnit ;
  :sepio/age-type ?ageType ;
  :sepio/age-value ?ageValue ;
  :sepio/ethnicity ?ethnicity ; 
  :sepio/previous-testing ?prevTesting ;
  :sepio/previous-testing-description ?prevTestingDescription ;
  :sepio/testing-methods ?methods ;
  :sepio/is-about-condition ?phenotypes ;

  :sepio/has-variant ?evidenceItem .

  ?family a :pco/Family ;
  :rdfs/label ?familyLabel ;
  :ro/has-member ?individual .

  ?functionEvidenceItem a :sepio/VariantFunctionalImpactEvidenceItem ;
  :dc/description ?functionalDataExplanation ;
  :sepio/functional-data-support ?functionalDataSupport .
}
where {

  ?evidenceLine a gci:variantScore ;
  gci:variantType ?variantType ;
  gci:variantScored ?variant ;
  gci:deNovo ?deNovo ;
  gci:scoreStatus ?scoreStatus ;
  gci:calculatedScore ?calculatedScore ;
  gci:date_created ?date_created .

  BIND(IF(?deNovo = "Yes", :geno/DeNovoAlleleOrigin , :geno/AlleleOrigin ) AS ?alleleOrigin) .
  
  OPTIONAL {
    ?evidenceLine gci:functionalDataExplanation ?functionalDataExplanation ;
    BIND(IRI(CONCAT(STR(?evidenceLine), "_function_evidence_item")) AS ?functionEvidenceItem) .
  }

  OPTIONAL {
    ?evidenceLine gci:functionalDataSupport ?functionalDataSupport .
  }

  BIND(IRI(CONCAT(STR(?evidenceLine), "_variant_evidence_item")) AS ?evidenceItem) .

  OPTIONAL {
    ?evidenceLine gci:scoreExplanation ?evidenceLineDescription .
  }
  
  ?variantType gcixform:hasEvidenceLineType ?evidenceLineType ;
  gcixform:hasEvidenceItemType ?evidenceItemType .

  OPTIONAL  {
    ?evidenceLine gci:score ?adjustedScore .
  }
  
  BIND(COALESCE(?adjustedScore, ?calculatedScore) AS ?baseScore) .

  ?individual gci:variantScores ?evidenceLine ;
  gci:label ?individualLabel ;

  gci:sex ?sex ;
  gci:proband true .

  OPTIONAL {
    ?individual gci:ageType ?ageType .
    ?individual gci:ageValue ?ageValue .
    ?individual gci:ageUnit ?ageUnit .
  }

  OPTIONAL {
    ?individual gci:hpoIdInDiagnosis ?phenotypeString .
    BIND(IRI(CONCAT("http://purl.obolibrary.org/obo/HP_", SUBSTR(?phenotypeString, STRLEN(?phenotypeString) - 7 , 7))) AS ?phenotypes) .
  }

  OPTIONAL {
    ?individual gci:ethnicity ?ethnicity .
  }

  ?individual gci:method ?method .

   OPTIONAL {
    ?method gci:genotypingMethods ?methods .
  }
  
  OPTIONAL {
    ?method gci:previousTesting ?prevTesting .
  }
  
  OPTIONAL {
    ?method gci:previousTestingDescription ?prevTestingDescription .
  }

  OPTIONAL {
    ?individual gci:recessiveZygosity ?zygosity .
  }

  BIND(IF( bound(?zygosity) && ?zygosity = :geno/Homozygous , ?baseScore * 2 , ?baseScore) AS ?score) .

  BIND(IF( bound(?zygosity) && ?zygosity = :geno/Homozygous , ?calculatedScore * 2 , ?calculatedScore) AS ?resultCalculatedScore) .
  
  ?annotation  gci:individuals|gci:individualIncluded ?individual ;
  ^gci:familyIncluded? / ^(gci:families|gci:groups)? / gci:article ?publication .

  OPTIONAL {
    ?family gci:individualIncluded ?individual ;
    gci:label ?familyLabel ;
    a gci:family .
  }

  ?publication gci:pmid ?pmid .
  BIND(IRI(CONCAT(?pmbase, ?pmid)) AS ?article) .
  
}
