prefix gci: <http://dataexchange.clinicalgenome.org/gci/>
construct 
{
  ?gdm a :sepio/GeneValidityProposition . 
  ?gdm :sepio/has-subject ?entrez_gene .
  ?gdm :sepio/has-predicate :ro/IsCausalGermlineMutationIn .
  ?gdm :sepio/has-object ?disease .
  ?gdm :sepio/has-qualifier ?moi .
}
where
{
  ?gdm a gci:gdm .


  # Includes support for pre-refactor GCI curations
  OPTIONAL {
    ?gdm gci:disease / gci:diseaseId ?legacy_disease
  }
  
  ?gdm gci:disease ?disease_node .

  BIND(COALESCE(?legacy_disease, ?disease_node) AS ?disease) .
  
  ?gdm gci:modeInheritance ?moistr .

  # The HPO term is embedded in a string, extract the digit and wrap in an IRI
  BIND(IRI(CONCAT("http://purl.obolibrary.org/obo/HP_", REPLACE(?moistr, "[^0-9]", ""))) AS ?moi) .
}
