construct {
  ?s ?p ?o .
}
where
{
  ?s ?p ?o .
  minus {
    ?s a :sepio/OverallGeneticEvidenceLine .
    [] :sepio/has-evidence ?o ;
    a :sepio/ProbandEvidenceLine .
    { ?o a :sepio/NullVariantEvidenceLine . } union
    { ?o a :sepio/NonNullVariantEvidenceLine . }
  }
}
