# Select the conditions associated with a gene via a curation.

select distinct ?disease
where {
  { ?validity_prop a :sepio/GeneValidityProposition ;
    :sepio/has-subject ?gene ;
    :sepio/has-object ?disease .
  } union {
    ?ac_prop a :sepio/ActionabilityReport ;
    :sepio/is-about-condition ?ac_genetic_cond .
    ?ac_genetic_cond :sepio/is-about-gene ?gene ;
    a :cg/ActionabilityGeneticCondition ;
    :owl/sub-class-of ?disease .
  } union {
    ?ac_prop a :sepio/ActionabilityReport ;
    :sepio/is-about-condition
  }
}
