# Cloud Build configuration for Genegraph
#
# Command line test usage:
# gcloud builds submit --project=clingen-stage --config ./cloudbuild.yaml \
#  --substitutions=COMMIT_SHA="testbuild" .

# Builds genegraph and tags for both stage and prod image repositories
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '.', '-t', 'genegraph:$COMMIT_SHA']
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'tag', 'genegraph:$COMMIT_SHA', 'gcr.io/clingen-stage/genegraph:$COMMIT_SHA']
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'tag', 'genegraph:$COMMIT_SHA', 'gcr.io/clingen-dx/genegraph:$COMMIT_SHA']
- name: 'gcr.io/cloud-builders/git'
  entrypoint: bash
  args: [
      '-c',
      'git log --format=format:%ae | head -n 1 > /workspace/author-email.txt
      && git log --format=format:%s | head -n 1 > /workspace/commit-title.txt
      && echo "Latest author: $(cat /workspace/author-email.txt) " > /workspace/body.txt
      && echo "Latest subject: $(cat /workspace/commit-title.txt)" >> /workspace/body.txt
      && if [[ ! -z "$TRIGGER_NAME" ]]; then echo "Trigger: $TRIGGER_NAME" >> /workspace/body.txt; fi
      && if [[ ! -z "$_PR_NUMBER" ]]; then echo "Cause PR: https://github.com/clingen-data-model/genegraph/pull/$_PR_NUMBER" >> /workspace/body.txt; fi']
- name: 'gcr.io/clingen-stage/git-image-updater'
  secretEnv: ["GITHUB_TOKEN"]
  args:
    - '-c'
    - |
      git clone https://clingen-ci:$$GITHUB_TOKEN@github.com/clingen-data-model/architecture \
      && cd architecture \
      && git checkout -b image-update-$SHORT_SHA \
      && /usr/bin/yq eval -i ".genegraph_docker_image_tag = \"$COMMIT_SHA\"" ./helm/values/genegraph/values-stage.yaml \
      && /usr/bin/yq eval -i ".genegraph_docker_image_tag = \"$COMMIT_SHA\"" ./helm/values/genegraph/values-prod.yaml \
      && date "+%Y-%m-%dT%H%M" > /workspace/DATETIME.txt \
      && /usr/bin/yq eval -i ".genegraph_data_version = \"$(tr -d '\n' < /workspace/DATETIME.txt):$COMMIT_SHA\"" ./helm/values/genegraph/values-stage.yaml \
      && /usr/bin/yq eval -i ".genegraph_data_version = \"$(tr -d '\n' < /workspace/DATETIME.txt):$COMMIT_SHA\"" ./helm/values/genegraph/values-prod.yaml \
      && git add -u \
      && git -c user.name="Clingen CI Automation" -c user.email="clingendevs@broadinstitute.org" commit -m "bumping docker image for genegraph" \
      && git push origin image-update-$SHORT_SHA \
      && gh pr create --fill -l automation -b "$(cat /workspace/body.txt)"

availableSecrets:
  secretManager:
    - versionName: projects/clingen-stage/secrets/clingen-ci-github-token/versions/2
      env: GITHUB_TOKEN

# push the images
images:
  - 'gcr.io/clingen-stage/genegraph:$COMMIT_SHA'
  - 'gcr.io/clingen-dx/genegraph:$COMMIT_SHA'

# timeout if not complete in 45 minutes
timeout: 2700s
