name: Linting

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master

jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - uses: hadolint/hadolint-action@v1.5.0
        with:
          dockerfile: Dockerfile
  clojure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: DeLaGuardo/setup-clj-kondo@v1
        with:
          version: "2022.05.31"
      - name: clj-kondo src/
        run: clj-kondo --lint src
