name: Linting

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master

jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - uses: hadolint/hadolint-action@v1.5.0
        with:
          dockerfile: Dockerfile
  clojure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: DeLaGuardo/clojure-lint-action@master
        with:
          clj-kondo-args: --lint src
          github_token: ${{ secrets.GITHUB_TOKEN }}
